# Generated by Django 5.2.4 on 2025-08-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('bio', models.TextField()),
                ('short_bio', models.TextField(blank=True, max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('historical', 'Historical'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('religious', 'Religious')], max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', '1-2 Years'), ('intermediate', '3-5 Years'), ('experienced', '6-10 Years'), ('expert', '10+ Years')], default='beginner', max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('languages', models.CharField(help_text='Comma-separated languages', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_tours', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
