from django.core.management.base import BaseCommand
from django.utils.text import slugify
from destination.models import Destination
from decimal import Decimal


class Command(BaseCommand):
    help = 'Populate the database with sample destinations'

    def handle(self, *args, **options):
        destinations_data = [
            {
                'name': "Cox's Bazar Sea Beach",
                'description': "Cox's Bazar is the longest natural sea beach in the world and one of the most popular tourist destinations in Bangladesh. The beach stretches for 120 km along the Bay of Bengal. Visitors can enjoy surfing, parasailing, and other water sports activities.",
                'short_description': "The world's longest natural sea beach offering stunning sunsets and water sports activities.",
                'location': "Cox's Bazar",
                'district': "Cox's Bazar",
                'division': 'Chittagong',
                'category': 'beach',
                'difficulty_level': 'easy',
                'entry_fee': Decimal('0.00'),
                'duration': '2-3 Days',
                'best_time_to_visit': 'October to March',
                'tour_price': Decimal('15000.00'),
                'tour_duration_days': 3,
                'max_group_size': 20,
                'tour_includes': 'Accommodation, Meals, Transportation, Guide',
                'tour_excludes': 'Personal expenses, Water sports equipment',
                'latitude': Decimal('21.427100'),
                'longitude': Decimal('92.006104'),
                'featured': True,
            },
            {
                'name': 'Sundarbans Mangrove Forest',
                'description': 'The Sundarbans is the largest mangrove forest in the world and a UNESCO World Heritage Site. It is home to the famous Royal Bengal Tiger and numerous other wildlife species. The forest covers about 10,000 square kilometers.',
                'short_description': 'UNESCO World Heritage Site and home to the Royal Bengal Tiger.',
                'location': 'Sundarbans',
                'district': 'Khulna',
                'division': 'Khulna',
                'category': 'adventure',
                'difficulty_level': 'moderate',
                'entry_fee': Decimal('500.00'),
                'duration': '3-4 Days',
                'best_time_to_visit': 'November to February',
                'tour_price': Decimal('25000.00'),
                'tour_duration_days': 4,
                'max_group_size': 15,
                'tour_includes': 'Boat transportation, Meals, Accommodation, Forest guide',
                'tour_excludes': 'Personal expenses, Camera fees',
                'latitude': Decimal('22.487700'),
                'longitude': Decimal('89.538900'),
                'featured': True,
            },
            {
                'name': 'Sajek Valley',
                'description': 'Sajek Valley is known as the "Queen of Hills" and "Roof of Rangamati". It offers breathtaking views of clouds, mountains, and tribal villages. The valley is perfect for trekking and experiencing indigenous culture.',
                'short_description': 'The Queen of Hills offering breathtaking mountain views and tribal culture.',
                'location': 'Sajek',
                'district': 'Rangamati',
                'division': 'Chittagong',
                'category': 'mountain',
                'difficulty_level': 'moderate',
                'entry_fee': Decimal('200.00'),
                'duration': '2-3 Days',
                'best_time_to_visit': 'October to April',
                'tour_price': Decimal('18000.00'),
                'tour_duration_days': 3,
                'max_group_size': 12,
                'tour_includes': 'Transportation, Accommodation, Meals, Local guide',
                'tour_excludes': 'Personal expenses, Trekking equipment',
                'latitude': Decimal('23.383300'),
                'longitude': Decimal('92.300000'),
                'featured': True,
            },
            {
                'name': 'Lalbagh Fort',
                'description': 'Lalbagh Fort is a 17th-century Mughal fort complex in Dhaka. Built by Prince Muhammad Azam Shah, it represents the golden age of Mughal architecture in Bengal. The fort houses a mosque, tomb, and beautiful gardens.',
                'short_description': 'Historic 17th-century Mughal fort showcasing magnificent architecture.',
                'location': 'Lalbagh',
                'district': 'Dhaka',
                'division': 'Dhaka',
                'category': 'historical',
                'difficulty_level': 'easy',
                'entry_fee': Decimal('20.00'),
                'duration': '2-3 Hours',
                'best_time_to_visit': 'October to March',
                'tour_price': Decimal('5000.00'),
                'tour_duration_days': 1,
                'max_group_size': 25,
                'tour_includes': 'Entry fees, Guide service',
                'tour_excludes': 'Transportation, Meals',
                'latitude': Decimal('23.718100'),
                'longitude': Decimal('90.386700'),
                'featured': False,
            },
            {
                'name': 'Srimangal Tea Gardens',
                'description': 'Srimangal is known as the tea capital of Bangladesh. The rolling hills covered with tea gardens offer a serene and picturesque landscape. Visitors can tour tea factories and enjoy fresh tea.',
                'short_description': 'Tea capital of Bangladesh with scenic rolling hills and tea gardens.',
                'location': 'Srimangal',
                'district': 'Moulvibazar',
                'division': 'Sylhet',
                'category': 'cultural',
                'difficulty_level': 'easy',
                'entry_fee': Decimal('100.00'),
                'duration': '1-2 Days',
                'best_time_to_visit': 'October to March',
                'tour_price': Decimal('12000.00'),
                'tour_duration_days': 2,
                'max_group_size': 18,
                'tour_includes': 'Accommodation, Tea garden tour, Meals',
                'tour_excludes': 'Personal expenses, Shopping',
                'latitude': Decimal('24.308300'),
                'longitude': Decimal('91.729200'),
                'featured': False,
            },
            {
                'name': 'Ahsan Manzil',
                'description': 'Known as the Pink Palace, Ahsan Manzil was the official residential palace of the Dhaka Nawab Family. Now a museum, it showcases the lifestyle and culture of the 19th-century aristocracy.',
                'short_description': 'The Pink Palace museum showcasing 19th-century aristocratic lifestyle.',
                'location': 'Kumartoli',
                'district': 'Dhaka',
                'division': 'Dhaka',
                'category': 'historical',
                'difficulty_level': 'easy',
                'entry_fee': Decimal('30.00'),
                'duration': '2-3 Hours',
                'best_time_to_visit': 'Year round',
                'tour_price': Decimal('4000.00'),
                'tour_duration_days': 1,
                'max_group_size': 30,
                'tour_includes': 'Entry fees, Museum guide',
                'tour_excludes': 'Transportation, Meals',
                'latitude': Decimal('23.708300'),
                'longitude': Decimal('90.406900'),
                'featured': False,
            },
            {
                'name': 'Saint Martin Island',
                'description': 'Saint Martin Island is the only coral island in Bangladesh. Known for its crystal clear water, coral reefs, and pristine beaches, it offers excellent opportunities for snorkeling and diving.',
                'short_description': "Bangladesh's only coral island with crystal clear waters and coral reefs.",
                'location': "Saint Martin's Island",
                'district': "Cox's Bazar",
                'division': 'Chittagong',
                'category': 'beach',
                'difficulty_level': 'easy',
                'entry_fee': Decimal('0.00'),
                'duration': '2-3 Days',
                'best_time_to_visit': 'November to March',
                'tour_price': Decimal('20000.00'),
                'tour_duration_days': 3,
                'max_group_size': 15,
                'tour_includes': 'Boat transportation, Accommodation, Meals',
                'tour_excludes': 'Snorkeling equipment, Personal expenses',
                'latitude': Decimal('20.626400'),
                'longitude': Decimal('92.322500'),
                'featured': True,
            },
            {
                'name': 'Sixty Dome Mosque',
                'description': 'The Sixty Dome Mosque in Bagerhat is a UNESCO World Heritage Site and one of the finest examples of Islamic architecture in Bangladesh. Built in the 15th century, it represents the golden period of Muslim architecture.',
                'short_description': 'UNESCO World Heritage Site showcasing 15th-century Islamic architecture.',
                'location': 'Bagerhat',
                'district': 'Bagerhat',
                'division': 'Khulna',
                'category': 'religious',
                'difficulty_level': 'easy',
                'entry_fee': Decimal('20.00'),
                'duration': '2-3 Hours',
                'best_time_to_visit': 'October to March',
                'tour_price': Decimal('6000.00'),
                'tour_duration_days': 1,
                'max_group_size': 25,
                'tour_includes': 'Entry fees, Historical guide',
                'tour_excludes': 'Transportation, Meals',
                'latitude': Decimal('22.651900'),
                'longitude': Decimal('89.944200'),
                'featured': False,
            },
            {
                'name': 'Rangamati Hanging Bridge',
                'description': 'Rangamati, known as the Lake City, features the famous hanging bridge over Kaptai Lake. The area offers boat rides, tribal culture experiences, and beautiful lake views surrounded by hills.',
                'short_description': 'Lake City featuring a famous hanging bridge and tribal culture.',
                'location': 'Rangamati',
                'district': 'Rangamati',
                'division': 'Chittagong',
                'category': 'adventure',
                'difficulty_level': 'easy',
                'entry_fee': Decimal('50.00'),
                'duration': '1-2 Days',
                'best_time_to_visit': 'October to April',
                'tour_price': Decimal('14000.00'),
                'tour_duration_days': 2,
                'max_group_size': 20,
                'tour_includes': 'Boat rides, Accommodation, Meals',
                'tour_excludes': 'Personal expenses, Shopping',
                'latitude': Decimal('22.627200'),
                'longitude': Decimal('92.198300'),
                'featured': False,
            },
            {
                'name': 'Bandarban Hill Tracts',
                'description': 'Bandarban is the highest hill district in Bangladesh, offering challenging treks, beautiful waterfalls, and encounters with indigenous communities. It includes popular spots like Nilgiri and Chimbuk Hill.',
                'short_description': 'Highest hill district offering challenging treks and beautiful waterfalls.',
                'location': 'Bandarban',
                'district': 'Bandarban',
                'division': 'Chittagong',
                'category': 'mountain',
                'difficulty_level': 'hard',
                'entry_fee': Decimal('100.00'),
                'duration': '3-5 Days',
                'best_time_to_visit': 'October to April',
                'tour_price': Decimal('22000.00'),
                'tour_duration_days': 4,
                'max_group_size': 10,
                'tour_includes': 'Trekking guide, Accommodation, Meals, Permits',
                'tour_excludes': 'Trekking equipment, Personal expenses',
                'latitude': Decimal('22.195100'),
                'longitude': Decimal('92.220400'),
                'featured': True,
            },
        ]

        created_count = 0
        for dest_data in destinations_data:
            # Generate slug from name
            dest_data['slug'] = slugify(dest_data['name'])
            
            # Check if destination already exists
            if not Destination.objects.filter(slug=dest_data['slug']).exists():
                destination = Destination.objects.create(**dest_data)
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f'Created destination: {destination.name}')
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f'Destination already exists: {dest_data["name"]}')
                )

        self.stdout.write(
            self.style.SUCCESS(f'\nSuccessfully created {created_count} destinations!')
        )