# Generated by Django 5.2.4 on 2025-08-14 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGuideBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('guide_type', models.CharField(choices=[('city_tour', 'City Tour Guide'), ('adventure', 'Adventure Guide'), ('cultural', 'Cultural Guide'), ('nature', 'Nature Guide'), ('historical', 'Historical Guide'), ('photography', 'Photography Guide')], max_length=50)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('service_date', models.DateField()),
                ('duration_hours', models.IntegerField(default=4)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('contact_phone', models.CharField(max_length=15)),
                ('special_requirements', models.TextField(blank=True)),
                ('languages_spoken', models.CharField(default='Bengali, English', max_length=200)),
                ('experience_years', models.IntegerField(default=1)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='destination.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local Guide Booking',
                'verbose_name_plural': 'Local Guide Bookings',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateField()),
                ('number_of_people', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('special_requests', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.destination')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='destination.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour Booking',
                'verbose_name_plural': 'Tour Bookings',
                'ordering': ['-booking_date'],
            },
        ),
    ]
