# Generated by Django 5.2.4 on 2025-08-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalGuideBooking',
        ),
    ]
