# Generated by Django 5.2.4 on 2025-08-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('historical', 'Historical'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('religious', 'Religious')], max_length=20)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration', models.CharField(default='1 Day', max_length=100)),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('tour_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour_duration_days', models.IntegerField(default=1)),
                ('max_group_size', models.IntegerField(default=10)),
                ('tour_includes', models.TextField(blank=True)),
                ('tour_excludes', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
