# Generated by Django 5.2.4 on 2025-07-31 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('historical', 'Historical'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('religious', 'Religious'), ('nature', 'Nature')], max_length=20)),
                ('main_image', models.ImageField(upload_to='destinations/images/')),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='destinations/images/')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='destinations/images/')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='destinations/images/')),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('duration', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='easy', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
