# Generated by Django 5.2.4 on 2025-08-01 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='available_dates',
            field=models.TextField(blank=True, help_text='Available tour dates'),
        ),
        migrations.AddField(
            model_name='destination',
            name='max_group_size',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='tour_duration_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='destination',
            name='tour_excludes',
            field=models.TextField(blank=True, help_text="What's not included"),
        ),
        migrations.AddField(
            model_name='destination',
            name='tour_includes',
            field=models.TextField(blank=True, help_text="What's included in the tour package"),
        ),
        migrations.AddField(
            model_name='destination',
            name='tour_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('historical', 'Historical'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('religious', 'Religious'), ('nature', 'Nature'), ('waterfall', 'Waterfall'), ('forest', 'Forest'), ('archaeological', 'Archaeological')], max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/images/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('tour_date', models.DateField()),
                ('number_of_people', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='destination.tourbooking')),
            ],
        ),
    ]
